### ISSUE TITLE
proxy issue?

### ISSUE THREAD

**Issue by jsastudent1** [wakestudents/IssueTracker#20]
Proxy has websites like hbo max for example not working? giving it an error code everytime you try to watch a movie or tv show you get an error code any answers?

**Comment by isteiger** [comment]
well, the proxy is a bit diff in how it works compared to others, let me check what I can do, also thanks for using github for ur issue, makes 2 way communication easier lol

**Comment by jsastudent1** [comment]
yea np i js wanted to watch south park and i got error coded like every time i had clicked on a certain episode but i'll try it again and see what will happen.

**Comment by isteiger** [comment]
yeah i get the same thing, probably some drm thing, ik netflix works tho. also for southpark if u just wanna watch the latest ep u can go to https://southpark.cc.com even tho its got ads. its also unblocked on wcpss chromebooks for whatever stupid reason.

**Comment by isteiger** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/39713548/224050652-1165ee5a-057f-4b8e-bfe1-ec466fd2bc32.png">
this is what I see in the console, so seems like proxy isn't passing the file along correctly

**Comment by jsastudent1** [comment]
yea that's what i keep seeing, is there just no fix or is the proxy just kind of being weird right now?

**Comment by isteiger** [comment]
with this proxy? no i dont think there is a fix, but I can see about other proxy software. different proxy software works differently, so my idea is making a super proxy site that automatically chooses the best software for the site. I'm gonna check at home about that tho bc its pretty weird considering everything else on the site works just fine

**Comment by jsastudent1** [comment]
yea since the act is goin on the internet is acting so weird right now so if you ever find a better proxy that uses the best software let me know.

**Comment by isteiger** [comment]
yup will do

**Comment by EVERYTHINGDEAD** [comment]
can we come up wihta new proxy like carbon when it unblocked everything in school
